

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: asow
    password: asow
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  springdoc.swagger-ui:
    enabled: true
    use-root-path: true
server:
  servlet:
    context-path: /api

